### ISSUE TITLE
根据教程使用弹窗空白

### ISSUE THREAD

**Issue by HC-miss** [MPComponent/mpvue-citypicker#24]
根据我自己的理解，做了如下两点：
1.  将源码`pickerChange`函数内的`let changePickerValue = e.mp.detail.value`变更为`let changePickerValue = e.detail.value`。
2.  将包裹`picker-view-column`的外层`block`移除，原因是官方文档有一项关于`picker-view`的提示: 其中只可放置 `<picker-view-column/>` 组件，其他节点不会显示。

```vue
<template>
	<div class="mpvue-picker">
		<div :class="{'pickerMask':showPicker}" @click="maskClick" catchtouchmove="true"></div>
		<div class="mpvue-picker-content " :class="{'mpvue-picker-view-show':showPicker}">
			<div class="mpvue-picker__hd" catchtouchmove="true">
				<div class="mpvue-picker__action" @click="pickerCancel">取消</div>
				<div class="mpvue-picker__action" :style="{color:themeColor}" @click="pickerConfirm">确定</div>
			</div>
			<picker-view indicator-style="height: 40px;" class="mpvue-picker-view" :value="pickerValue" @change="pickerChange">
				<picker-view-column>
					<div class="picker-item" v-for="(item,index) in provinceDataList" :key="index">{{item.label}}</div>
				</picker-view-column>
				<picker-view-column>
					<div class="picker-item" v-for="(item,index) in cityDataList" :key="index">{{item.label}}</div>
				</picker-view-column>
				<picker-view-column>
					<div class="picker-item" v-for="(item,index) in areaDataList" :key="index">{{item.label}}</div>
				</picker-view-column>
			</picker-view>
		</div>
	</div>
</template>

<script>
...
pickerChange(e) {
// let changePickerValue = e.mp.detail.value;
let changePickerValue = e.detail.value;
if (this.pickerValue[0] !== changePickerValue[0]) {
	// 第一级发生滚动
	this.cityDataList = cityData[changePickerValue[0]];
	this.areaDataList = areaData[changePickerValue[0]][0];
	changePickerValue[1] = 0;
	changePickerValue[2] = 0;
} else if (this.pickerValue[1] !== changePickerValue[1]) {
	// 第二级滚动
	this.areaDataList =
		areaData[changePickerValue[0]][changePickerValue[1]];
	changePickerValue[2] = 0;
}
this.pickerValue = changePickerValue;
this._$emit('onChange');
},
...
</script>

**Comment by HC-miss** [comment]
> 根据我自己的理解，做了如下两点：
> 
> 1. 将源码`pickerChange`函数内的`let changePickerValue = e.mp.detail.value`变更为`let changePickerValue = e.detail.value`。
> 2. 将包裹`picker-view-column`的外层`block`移除，原因是官方文档有一项关于`picker-view`的提示: 其中只可放置 `<picker-view-column/>` 组件，其他节点不会显示。
> 
> ```
> <template>
> 	<div class="mpvue-picker">
> 		<div :class="{'pickerMask':showPicker}" @click="maskClick" catchtouchmove="true"></div>
> 		<div class="mpvue-picker-content " :class="{'mpvue-picker-view-show':showPicker}">
> 			<div class="mpvue-picker__hd" catchtouchmove="true">
> 				<div class="mpvue-picker__action" @click="pickerCancel">取消</div>
> 				<div class="mpvue-picker__action" :style="{color:themeColor}" @click="pickerConfirm">确定</div>
> 			</div>
> 			<picker-view indicator-style="height: 40px;" class="mpvue-picker-view" :value="pickerValue" @change="pickerChange">
> 				<picker-view-column>
> 					<div class="picker-item" v-for="(item,index) in provinceDataList" :key="index">{{item.label}}</div>
> 				</picker-view-column>
> 				<picker-view-column>
> 					<div class="picker-item" v-for="(item,index) in cityDataList" :key="index">{{item.label}}</div>
> 				</picker-view-column>
> 				<picker-view-column>
> 					<div class="picker-item" v-for="(item,index) in areaDataList" :key="index">{{item.label}}</div>
> 				</picker-view-column>
> 			</picker-view>
> 		</div>
> 	</div>
> </template>
> 
> <script>
> ...
> pickerChange(e) {
> // let changePickerValue = e.mp.detail.value;
> let changePickerValue = e.detail.value;
> if (this.pickerValue[0] !== changePickerValue[0]) {
> 	// 第一级发生滚动
> 	this.cityDataList = cityData[changePickerValue[0]];
> 	this.areaDataList = areaData[changePickerValue[0]][0];
> 	changePickerValue[1] = 0;
> 	changePickerValue[2] = 0;
> } else if (this.pickerValue[1] !== changePickerValue[1]) {
> 	// 第二级滚动
> 	this.areaDataList =
> 		areaData[changePickerValue[0]][changePickerValue[1]];
> 	changePickerValue[2] = 0;
> }
> this.pickerValue = changePickerValue;
> this._$emit('onChange');
> },
> ...
> </script>
> ```



> 根据我自己的理解，做了如下两点：
> 
> 1. 将源码`pickerChange`函数内的`let changePickerValue = e.mp.detail.value`变更为`let changePickerValue = e.detail.value`。
> 2. 将包裹`picker-view-column`的外层`block`移除，原因是官方文档有一项关于`picker-view`的提示: 其中只可放置 `<picker-view-column/>` 组件，其他节点不会显示。
> 
> ```
> <template>
> 	<div class="mpvue-picker">
> 		<div :class="{'pickerMask':showPicker}" @click="maskClick" catchtouchmove="true"></div>
> 		<div class="mpvue-picker-content " :class="{'mpvue-picker-view-show':showPicker}">
> 			<div class="mpvue-picker__hd" catchtouchmove="true">
> 				<div class="mpvue-picker__action" @click="pickerCancel">取消</div>
> 				<div class="mpvue-picker__action" :style="{color:themeColor}" @click="pickerConfirm">确定</div>
> 			</div>
> 			<picker-view indicator-style="height: 40px;" class="mpvue-picker-view" :value="pickerValue" @change="pickerChange">
> 				<picker-view-column>
> 					<div class="picker-item" v-for="(item,index) in provinceDataList" :key="index">{{item.label}}</div>
> 				</picker-view-column>
> 				<picker-view-column>
> 					<div class="picker-item" v-for="(item,index) in cityDataList" :key="index">{{item.label}}</div>
> 				</picker-view-column>
> 				<picker-view-column>
> 					<div class="picker-item" v-for="(item,index) in areaDataList" :key="index">{{item.label}}</div>
> 				</picker-view-column>
> 			</picker-view>
> 		</div>
> 	</div>
> </template>
> 
> <script>
> ...
> pickerChange(e) {
> // let changePickerValue = e.mp.detail.value;
> let changePickerValue = e.detail.value;
> if (this.pickerValue[0] !== changePickerValue[0]) {
> 	// 第一级发生滚动
> 	this.cityDataList = cityData[changePickerValue[0]];
> 	this.areaDataList = areaData[changePickerValue[0]][0];
> 	changePickerValue[1] = 0;
> 	changePickerValue[2] = 0;
> } else if (this.pickerValue[1] !== changePickerValue[1]) {
> 	// 第二级滚动
> 	this.areaDataList =
> 		areaData[changePickerValue[0]][changePickerValue[1]];
> 	changePickerValue[2] = 0;
> }
> this.pickerValue = changePickerValue;
> this._$emit('onChange');
> },
> ...
> </script>
> ```

当然，仅针对移动端和H5，因为我只参考这两个写代码:rofl:

**Comment by KuangPF** [comment]
这个包是小程序端直接使用，其他平台未做适配。
