### ISSUE TITLE
在uni-app中使用报warn

### ISSUE THREAD

**Issue by arthasshi** [MPComponent/mpvue-citypicker#4]
> [Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "showPicker"
11:39:59.951 found in
11:39:59.951 ---> node-modules/_mpvue-citypicker@1.0.5@mpvue-citypicker/src/mpvueCityPicker
## 因为我只在mpvue中使用了，所以只发现这里报错

**Comment by KuangPF** [comment]
嫩否提供下具体的代码呢，我这边使用下面的的代码没有复现这个问题
``` vue
<template>
  <div class="mpvue-city-picker">
    <button type="default" @click="showCityPicker">城市选择</button>
    <mpvue-city-picker ref="mpvueCityPicker" :pickerValueDefault="pickerValueDefault" :themeColor='themeColor'></mpvue-city-picker>
  </div>
</template>

<script>
import mpvueCityPicker from 'mpvue-citypicker';
export default {
  data() {
    return {
      pickerValueDefault: [0, 0, 1],
      themeColor: '#4A8AE9'
    };
  },
  components: {
    mpvueCityPicker
  },
  methods: {
    showCityPicker() {
      this.$refs.mpvueCityPicker.show();
    }
  }
};
</script>
<style>
</style>
```

**Comment by transno** [comment]
@KuangPF 我直接使用了你提供的这段代码也出现了同样的错误提示

**Comment by KuangPF** [comment]
`v1.0.6` 已修复。
