### ISSUE TITLE
默认值选择广东省无效

### ISSUE THREAD

**Issue by yanjingyun** [MPComponent/mpvue-citypicker#5]
<template>
	<view>
		<button type="default" @tap="showCityPicker">行政区划联动</button>
		<mpvue-city-picker ref="mpvueCityPicker" :pickerValueDefault="pickerValueDefault" @onChange="onChange" @onCancel="onCancel"
		 @onConfirm="onConfirm"></mpvue-city-picker>
	</view>
</template>

<script>
	import mpvueCityPicker from '@/components/mpvue-citypicker/mpvueCityPicker';

	export default {
		components: {
			mpvueCityPicker
		},
		data() {
			return {
				pickerValueDefault: [18, 2, 3]
			}
		},
		onLoad() {

		},
		methods: {
			// 二级联动选择
			showCityPicker() {
				this.$refs.mpvueCityPicker.show();
			},
			onChange(e) {
				console.log(e);
			},
			onCancel(e) {
				console.log(e);
			},
			onConfirm(e) {
				console.log(e);
			}
		}
	}
</script>

<style>
</style>

**Comment by KuangPF** [comment]
`mpvue-citypicker` 版本号多少，我这边不能复现。

**Comment by yanjingyun** [comment]
哈哈哈，其实也不知道，后面看了你们的源码，发现用的picker-view这个组件的，然后后面的下标修改都是直接在你们的mpvue-city-picker.vue这个文件里面修改的（可行），谢谢你啦
