### ISSUE TITLE
设置默认值后，省份和区可以命中，城市一直是命中索引0位置上的

### ISSUE THREAD

**Issue by perryzhangateosi** [MPComponent/mpvue-citypicker#6]
![image](https://user-images.githubusercontent.com/17328938/60314280-aee58e00-9994-11e9-9808-ae751e2725ed.png)

**Comment by KuangPF** [comment]
你使用的是 `uni-app` 提供的插件还是 `npm`上的包？

**Comment by perryzhangateosi** [comment]
> 你使用的是 `uni-app` 提供的插件还是 `npm`上的包？

使用的是uni的插件，干净的范例（未整合进我项目）也是一样。

**Comment by KuangPF** [comment]
`uni-app` 插件不是我在维护，你要在 `uni-app` 中用的话就直接通过 `npm` 包的方式引入。

**Comment by yuanxiongwei** [comment]
npm的包也是一样。使用最新的源码编译也是一样的
